spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    url: ${SPRING_DATASOURCE_URL}
  jpa:
    hibernate:
      ddl-auto: none
    open-in-view: true
  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
            required: true
          from: ${MAIL_FROM}
  flyway:
    baseline-on-migrate: true
    enabled: true

jwt:
  secret:
    key: ${JWT_SECRET_KEY}

server:
  servlet:
    context-path: /api # all routes in this app will be prefixed with this
    session:
      cookie:
        same-site: none
        secure: true
  forward-headers-strategy: framework

app:
  frontend-url: ${FRONTEND_URL}
